language: cpp

sudo: required

compiler:
    - clang
    - gcc

script:
    - cp libs/deps-example.yml deps.yml
    - python cdep.py
    - ls third-party/include
    - ls third-party/libs
    - cd tests && make
    - bash tests/test_all.sh
