language: cpp

sudo: required

compiler:
    - clang
    - gcc

before_install:
    - '[[ $CC == gcc ]] && sudo add-apt-repository ppa:ubuntu-toolchain-r/test'
    - '[[ $CC == gcc ]] && sudo apt-get update'
    - '[[ $CC == gcc ]] && sudo apt-get install gcc-4.7'

script:
    - cp libs/deps-example.yml deps.yml
    - python cdep.py
    - ls third-party/include
    - ls third-party/libs
    - cd tests && make
    - bash tests/test_all.sh
