language: c

sudo: required

compiler:
    - clang
    - gcc

script:
    - cp libs/deps-example.yml deps.yml
    - python cdep.py
    - ls third-party/include
    - ls third-party/libs
    - if [[ $CC == 'gcc' ]]; then cd tests && CPP='g++' make fi
    - if [[ $CC == 'clang' ]]; then cd tests && CPP='clang++' make fi
    - bash tests/test_all.sh
