language: cpp

sudo: required

compiler:
    - clang
    - gcc

before_install:
    - |
      if [[ $CC == gcc ]]; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y gcc-4.7
      else
        echo ignore
      fi

script:
    - cp libs/deps-example.yml deps.yml
    - python cdep.py
    - ls third-party/include
    - ls third-party/libs
    - cd tests && make
    - bash tests/test_all.sh
